development:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: discover_shows_production
  pool: 5
