# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba82febbf54438b66c7efc362062695ce8b72e365a85686f3803d1cc07b0f2ca7ddd9b57903718f441cba8629924935dd5adb7f0e9387d012d3954625cdbb97

test:
  secret_key_base: 7e517516bfac98c7a812ac47eceacd78cd8f2f1c17b46909ed083d755f1f3dfce1ae3d87f60c75ad5e89e52313a1472af72bda0b6f1152345c5ca9892475ee99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
