MuscleGroup.create(name: "Chest")
MuscleGroup.create(name: "Back")
MuscleGroup.create(name: "Legs")
MuscleGroup.create(name: "Shoulders")
MuscleGroup.create(name: "Bis")
MuscleGroup.create(name: "Tris")
MuscleGroup.create(name: "Abs")
MuscleGroup.create(name: "Cardio")
